### ISSUE TITLE
Great piece of code!

### ISSUE THREAD

**Issue by jvinolas** [zom-bi/zomstream#1]
Great! I was looking for something like this. I'm working on it to add some features we need (like recording) in my fork. I'll let you know when I'm finish with it!

**Comment by sixohsix** [comment]
@jvinolas I tried using your fork, which seems to have some cool changes. However, when I can't get it to run because it's missing `convert.sh`. Could you add and push that file?

Also, you turned off issues on your repo, so I can't report this to you there. (Sorry, zom-bi, for disturbing you.)
