### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by ilpiruz** [zom-bi/zomstream#14]
i don't know how to use this
(i don't know how to setup)
p.s.: i followed the setup instructions but i still don't know how to setup

**Comment by qamodi** [comment]
Can you provide some more information? With what part of the setup instructions are you struggling?

**Comment by ilpiruz** [comment]
> Can you provide some more information? With what part of the setup instructions are you struggling?

i don't know how to setup.
i didn't find the files that i have to copy to

**Comment by qamodi** [comment]
find the frontend config in [config/frontend](https://github.com/zom-bi/zomstream/blob/master/config/frontend/config.example.yml)
The [docker-compose.default.yml](https://github.com/zom-bi/zomstream/blob/master/docker-compose.default.yml) is in the root directory of the repository.

**Comment by ilpiruz** [comment]
thanks
